<a href="https://colab.research.google.com/github/dino340/Candev-PDF-Parser/blob/main/Camelot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# install dependencies

! pip install "camelot-py[base]"
! apt install ghostscript

In [2]:
# set pdf input folder and json output folders
pdf_folder  = '/content/drive/MyDrive/pdf_output/'
json_output = '/content/drive/MyDrive/json_output/'

In [6]:
# create output folder if it does not exist

if os.path.isdir(json_output) == False:
  os.mkdir(json_output)

In [3]:
import camelot
import os

In [4]:
# generate list of pdfs to scrape
files = []
for file_name in os.listdir(pdf_folder):
  if file_name.endswith('pdf'):
    files.append(file_name)

In [8]:
# example of output in a pandas dataframe

table_example = camelot.read_pdf('/content/drive/MyDrive/pdf_output/CHIPPEWAS_OF_RAMA_FIRST_NATION__ON_2019-20.pdf', flavor='stream',pages='all')
table_example[8].df

                                                    0  ...             5
0                                                      ...
1                         For the year ended March 31  ...
2                                                      ...          2019
3                            Annual surplus (deficit)  ...
4                                                      ...  $105,174,067
5              Acquisition of tangible capital assets  ...   (2,692,941)
6             Amortization of tangible capital assets  ...
7                                                      ...     4,344,948
8   Loss (gain) on disposal of tangible capital as...  ...      (68,621)
9      Proceeds on disposalof tangible capital assets  ...       232,481
10                                                     ...   106,989,934
11                Use/consumption of prepaid expenses  ...
12                                                     ...       131,199
13        Use/consumption of inventories held for use  ...
14                                                     ...      (17,066)
15                                                     ...       114,133
16        Increase (decrease) in net financial assets  ...   107,104,067

[17 rows x 6 columns]

In [ ]:
# cycle through all PDFs in specified folder and export all detected tables as JSON files to specified output folder

for pdfname in files:
  pdf_path = pdf_folder + pdfname
  output_path = json_output + pdfname + '/'
  if os.path.isdir(output_path) == False:
    os.mkdir(output_path)
  tables = camelot.read_pdf(pdf_path, flavor='stream', pages='all')
  for i in range(0,len(tables)):
    tables[i].to_json(f'{output_path}{pdfname}_table{i+1}.json')